### ISSUE TITLE
Job hangs when available hosts < min hosts instead of terminating

### ISSUE THREAD

**Issue by srinathgit** [marklogic/java-client-api#577]
A. This test was run on a 3 node cluster (rh7v-intel64-90-test-4/5/6.marklogic.com) with a forest (ApplyTransform1,2,3) on each of the node associated with a db.
B. Now when 'batcher ' QB job is getting executed,nodes rh7v-intel64-90-test-5/6.marklogic.com are stopped one after the other.
```
 new HostAvailabilityListener(dmManager)
  .withSuspendTimeForHostUnavailable(Duration.ofSeconds(15))
   .withMinHosts(2)
```

C.From the log, it can be seen that rh7v-intel64-90-test-6.marklogic.com is black listed but once rh7v-intel64-90-test-5.marklogic.com is stopped , it is not black listed.
D. Instead,the process hangs forever. The stack trace and client logs are attached.

[Client log](https://github.com/marklogic/java-client-api/files/629343/exception1.txt)
[jstack.txt](https://github.com/marklogic/java-client-api/files/629344/jstack.txt)

```
	@Test
	public void xQueryMasstransformReplace() throws Exception{
		
		WriteBatcher ihb2 =  dmManager.newWriteBatcher();
		ihb2.withBatchSize(27).withThreadCount(10);
		ihb2.onBatchSuccess(
				batch -> {


				}
				)
		.onBatchFailure(
				(batch, throwable) -> {
					throwable.printStackTrace();
				});

		dmManager.startJob(ihb2);
		
		for (int j =0 ;j < 2000; j++){
			String uri ="/local/string-"+ j;
			ihb2.add(uri, meta2, stringHandle);
		}

		ihb2.flushAndWait();

		ServerTransform transform = new ServerTransform("add-attr-xquery-transform");
		transform.put("name", "Lang");
		transform.put("value", "English");

		AtomicInteger skipped = new AtomicInteger(0);
		AtomicInteger success = new AtomicInteger(0);
		AtomicInteger failure = new AtomicInteger(0);

		ApplyTransformListener listener = new ApplyTransformListener()
				.withTransform(transform)
				.withApplyResult(ApplyResult.REPLACE)
				.onSuccess(batch -> {
					success.addAndGet(batch.getItems().length);
				}). 
				onBatchFailure((batch, throwable) -> {
					failure.addAndGet(batch.getItems().length);
					throwable.printStackTrace();
				}).onSkipped(batch -> {
					skipped.addAndGet(batch.getItems().length);

				});

		QueryBatcher batcher = dmManager.newQueryBatcher(new StructuredQueryBuilder().collection("XmlTransform"))
				.onUrisReady(listener).withBatchSize(7);
		batcher.setQueryFailureListeners(
				  new HostAvailabilityListener(dmManager)
				    .withSuspendTimeForHostUnavailable(Duration.ofSeconds(15))
				    .withMinHosts(2)
				);	
		JobTicket ticket = dmManager.startJob( batcher );
		batcher.awaitCompletion();
		dmManager.stopJob(ticket);
		System.out.println("Success "+ success.intValue());
		System.out.println("Failure "+failure.intValue());
		String uris[] = new String[2000];
		for(int i =0;i<2000;i++){
			uris[i] = "/local/string-"+ i;
		}
		int count=0;
		DocumentPage page = dbClient.newDocumentManager().read(uris);
		DOMHandle dh = new DOMHandle();
		while(page.hasNext()){
			DocumentRecord rec = page.next();
			rec.getContent(dh);
			assertTrue("Element has attribure ? :",dh.get().getElementsByTagName("foo").item(0).hasAttributes());
			assertEquals("Attribute value should be English","English",dh.get().getElementsByTagName("foo").item(0).getAttributes().item(0).getNodeValue());
			count++;
		}

		assertEquals("document count", 2000,count); 
		assertEquals("document count", 2000,success.intValue()); 
		assertEquals("document count", 0,skipped.intValue()); 
	}
```

**Comment by sammefford** [comment]
Can you tell me if there are enough replica forests on the remaining host?  Are we possibly dealing with the database becoming unavailable?  If so, I think I've seen connections hang for up to transaction timeout, which I believe is 10 mins by default.

**Comment by srinathgit** [comment]
The database becomes unavailable when two nodes ( rh7v-intel64-90-test-5/6.marklogic.com ) are stopped (available host then becomes 1 and 'minHosts'  is set to 2).  It can be seen that when first rh7v-intel64-90-test-6.marklogic.com is stopped , it is blacklisted (even before forest on rh7v-intel64-90-test-6.marklogic.com failed over). But shouldn't the same happen (blacklisting and eventually stopping the job on the client side) occur when rh7v-intel64-90-test-5.marklogic.com is stopped

**Comment by sammefford** [comment]
I found out while investigating #595 that calling datamovementManager.stopJob inside a listener (including HostAvailabilityListener) would hang the job. That's because stopJob was calling awaitCompletion() which waits for the listener to complete, which creates a type of deadlock. I committed [a fix](https://github.com/marklogic/java-client-api/commit/150759f7232ad3ac46bee993f9919c932ea21a4f) that makes it so stopJob doesn't call awaitCompletion().  That might fix this issue.  We need to verify.

**Comment by srinathgit** [comment]
This issue still occurs. The process hangs on awaitCompletion(). I have attached the latest stacktrace, client log. This test was run on a 3 node cluster (rh7v-intel64-90-test-19/20/21.marklogic.com) with a forest (ApplyTransform1,2,3) on each of the node associated with a db.

[stacktrace](https://github.com/marklogic/java-client-api/files/891734/stacktrace.txt)
[clientLog](https://github.com/marklogic/java-client-api/files/891737/exception.txt)

**Comment by vivekmuniyandi** [comment]
From what I understand here is, after the second node is brought down, the forest goes to a disabled state even though it is configured for failover. And it doesn't fail over. We indeed shut down the threadpool and all queued tasks but this process hangs because the request sent to the REST layer takes a long time to return. It does indeed exit after we get the reply from the REST layer but it takes a long time and the error we get is because of the forest being disabled and not failed over. We have to check this in the stress cluster to check if that is what is happening. If yes, then I think it should be a bug on the server. Thanks.

**Comment by vivekmuniyandi** [comment]
> It can be seen that when first rh7v-intel64-90-test-6.marklogic.com is stopped , it is blacklisted (even before forest on rh7v-intel64-90-test-6.marklogic.com failed over). But shouldn't the same happen (blacklisting and eventually stopping the job on the client side) occur when rh7v-intel64-90-test-5.marklogic.com is stopped

The same is happening. The stop job is called on the client side and there are no further requests submitted. But we have no way to control the inflight requests to the server. Since two of the three hosts are down, we are dealing with the database being unavailable situation and connections hang for up to transaction timeout. I see that the requests come back after the transaction time out and the job ends.

**Comment by vivekmuniyandi** [comment]
Kindly let me know if you feel otherwise.
